
HADOOP:
  - config_type: core-site
    hadoop.ssl.require.client.cert: false
    hadoop.ssl.hostname.verifier: DEFAULT
    hadoop.ssl.keystores.factory.class: org.apache.hadoop.security.ssl.FileBasedKeyStoresFactory
    hadoop.ssl.server.conf: ssl-server.xml
    hadoop.ssl.client.conf: ssl-client.xml

  - config_type: ssl-server
    ssl.server.keystore.keypassword: $keystorepassword
    ssl.server.keystore.password: $keystorepassword
    ssl.server.keystore.location: $keystore
    ssl.server.truststore.location: $truststore
    ssl.server.truststore.password: $truststorepassword

  - config_type: ssl-client
    ssl.client.keystore.location: $keystore
    ssl.client.keystore.password: $keystorepassword
    ssl.client.truststore.location: $truststore
    ssl.client.truststore.password: $truststorepassword

HDFS:
  - config_type: core-site
    hadoop.rpc.protection: privacy

  - config_type: hdfs-site
    dfs.encrypt.data.transfer: true
    dfs.encrypt.data.transfer.algorithm: 3des
    dfs.client.https.need-auth: false

HDFSUI:
  - config_type: hdfs-site
    dfs.http.policy: HTTP_AND_HTTPS
    dfs.namenode.https-address: 0.0.0.0:50470
    dfs.namenode.secondary.https-address: 0.0.0.0:50091

MRSHUFFLE:
  - config_type: mapred-site
    mapreduce.shuffle.ssl.enabled: false

MAPREDUCE2UI:
  - config_type: mapred-site
    mapreduce.jobhistory.http.policy: HTTPS_ONLY
    mapreduce.jobhistory.webapp.https.address: 0.0.0.0:19890

  - config_type: hdfs-site
    dfs.https.enable: true

YARN:
  - config_type: yarn-site
    yarn.http.policy: HTTPS_ONLY
    yarn.log.server.url: $historyserver
    yarn.log.server.web-service.url: $timelineserver
    yarn.nodemanager.webapp.https.address: 0.0.0.0:8044

  - config_type: hdfs-site
    dfs.https.enable: true

TEZ:
  - config_type: tez-site
    tez.runtime.shuffle.ssl.enable: shuffle
    tez.runtime.shuffle.keep-alive.enabled: true


KAFKA:
  - config_type: kafka-broker
    listeners: SASL_PLAINTEXT://localhost:6667,SASL_SSL://localhost:6668
    security.inter.broker.protocol: SASL_SSL
    ssl.keystore.location: $keystore
    ssl.keystore.password: $keystorepassword
    ssl.key.password: $keystorepassword
    ssl.truststore.location: $truststore
    ssl.truststore.password: $truststorepassword

HIVE:
  - config_type: hive-site
    hive.server2.thrift.sasl.qop: auth-conf
    hive.server2.use.SSL: true
    hive.server2.webui.use.ssl: true
    hive.server2.keystore.path: $keystore
    hive.server2.keystore.password: $keystorepassword    
    hive.server2.webui.keystore.path: $keystore
    hive.server2.webui.keystore.password: $keystorepassword
    hive.server2.truststore.path: $truststore
    hive.server2.truststore.password: $truststorepassword

  - config_type: hiveserver2-site
    hive.server2.keystore.path: $keystore
    hive.server2.keystore.password: $keystorepassword
    hive.server2.webui.keystore.path: $keystore
    hive.server2.webui.keystore.password: $keystorepassword
    hive.server2.truststore.path: $truststore
    hive.server2.truststore.password: $truststorepassword

  - config_type: hive-interactive-site
    hive.server2.thrift.sasl.qop: auth-conf
    hive.server2.use.SSL: true
    hive.server2.webui.use.ssl: true
    hive.server2.keystore.path: $keystore
    hive.server2.keystore.password: $keystorepassword
    hive.server2.webui.keystore.path: $keystore
    hive.server2.webui.keystore.password: $keystorepassword
    hive.server2.truststore.path: $truststore
    hive.server2.truststore.password: $truststorepassword

ZEPPELIN:
  - config_type: zeppelin-site
    zeppelin.ssl: true
    zeppelin.ssl.client.auth: false
    zeppelin.ssl.key.manager.password: $keystorepassword
    zeppelin.ssl.keystore.password: $keystorepassword
    zeppelin.ssl.keystore.path: $keystore
    zeppelin.ssl.keystore.type: JKS
    zeppelin.ssl.truststore.password: $truststorepassword
    zeppelin.ssl.truststore.path: $keystore
    zeppelin.ssl.truststore.type: JKS

AMBARI_INFRA_SOLR:
  - config_type: infra-solr-env
    infra_solr_ssl_enabled: true
    infra_solr_keystore_location: $keystore
    infra_solr_keystore_password: $keystorepassword
    infra_solr_truststore_location: $truststore
    infra_solr_truststore_password: $truststorepassword
    infra_solr_extra_java_opts: -Dsolr.ssl.checkPeerName=false

RANGERKMS:
  - config_type: ranger-kms-site
    ranger.service.https.attrib.client.auth: want
    ranger.service.https.attrib.keystore.file: $keystore
    ranger.service.https.attrib.keystore.pass: $keystorepassword
    ranger.service.https.attrib.keystore.keyalias: host_ssl
    ranger.service.https.attrib.ssl.enabled: true

  - config_type: kms-env
    kms_port: 9393

RANGERADMIN:
  - config_type: ranger-admin-site
    ranger.service.http.enabled: false
    ranger.https.attrib.keystore.file: $keystore
    ranger.service.https.attrib.keystore.pass: $keystorepassword
    ranger.service.https.attrib.keystore.keyalias: host_ssl
    ranger.service.https.attrib.clientAuth: want
    ranger.service.https.attrib.ssl.enabled: true
    ranger.service.https.port: 6182
    ranger.truststore.alias: host_ssl
    ranger.truststore.file: $truststore
    ranger.truststore.password: $truststorepassword
    ranger.service.https.attrib.keystore.file: $keystore
    ranger.service.https.attrib.client.auth: want

  - config_type: ranger-tagsync-policymgr-ssl
    xasecure.policymgr.clientssl.keystore: $keystore
    xasecure.policymgr.clientssl.keystore.password: $keystorepassword
    xasecure.policymgr.clientssl.truststore: $truststore
    xasecure.policymgr.clientssl.truststore.password: $truststorepassword

  - config_type: ranger-ugsync-site
    ranger.usersync.truststore.file: $truststore
    ranger.usersync.truststore.password: $truststorepassword
    ranger.usersync.keystore.file: $keystore
    ranger.usersync.keystore.password: $keystorepassword

RANGERPLUGINS:
  - config_type: ranger-hdfs-policymgr-ssl
    xasecure.policymgr.clientssl.keystore: $keystore
    xasecure.policymgr.clientssl.keystore.password: $keystorepassword
    xasecure.policymgr.clientssl.truststore: $truststore
    xasecure.policymgr.clientssl.truststore.password: $truststorepassword

  - config_type: ranger-yarn-policymgr-ssl
    xasecure.policymgr.clientssl.keystore: $keystore
    xasecure.policymgr.clientssl.keystore.password: $keystorepassword
    xasecure.policymgr.clientssl.truststore: $truststore
    xasecure.policymgr.clientssl.truststore.password: $truststorepassword

  - config_type: ranger-hive-policymgr-ssl
    xasecure.policymgr.clientssl.keystore: $keystore
    xasecure.policymgr.clientssl.keystore.password: $keystorepassword
    xasecure.policymgr.clientssl.truststore: $truststore
    xasecure.policymgr.clientssl.truststore.password: $truststorepassword

  - config_type: ranger-hbase-policymgr-ssl
    xasecure.policymgr.clientssl.keystore: $keystore
    xasecure.policymgr.clientssl.keystore.password: $keystorepassword
    xasecure.policymgr.clientssl.truststore: $truststore
    xasecure.policymgr.clientssl.truststore.password: $truststorepassword

  - config_type: ranger-atlas-policymgr-ssl
    xasecure.policymgr.clientssl.keystore: $keystore
    xasecure.policymgr.clientssl.keystore.password: $keystorepassword
    xasecure.policymgr.clientssl.truststore: $truststore
    xasecure.policymgr.clientssl.truststore.password: $truststorepassword

  - config_type: ranger-knox-policymgr-ssl
    xasecure.policymgr.clientssl.keystore: $keystore
    xasecure.policymgr.clientssl.keystore.password: $keystorepassword
    xasecure.policymgr.clientssl.truststore: $truststore
    xasecure.policymgr.clientssl.truststore.password: $truststorepassword

  - config_type: ranger-storm-policymgr-ssl
    xasecure.policymgr.clientssl.keystore: $keystore
    xasecure.policymgr.clientssl.keystore.password: $keystorepassword
    xasecure.policymgr.clientssl.truststore: $truststore
    xasecure.policymgr.clientssl.truststore.password: $truststorepassword

  - config_type: ranger-kafka-policymgr-ssl
    xasecure.policymgr.clientssl.keystore: $keystore
    xasecure.policymgr.clientssl.keystore.password: $keystorepassword
    xasecure.policymgr.clientssl.truststore: $truststore
    xasecure.policymgr.clientssl.truststore.password: $truststorepassword

  - config_type: atlas-tagsync-ssl
    xasecure.policymgr.clientssl.keystore: $keystore
    xasecure.policymgr.clientssl.keystore.password: $keystorepassword
    xasecure.policymgr.clientssl.truststore: $truststore
    xasecure.policymgr.clientssl.truststore.password: $truststorepassword

  - config_type: ranger-kms-policymgr-ssl
    xasecure.policymgr.clientssl.keystore: $keystore
    xasecure.policymgr.clientssl.keystore.password: $keystorepassword
    xasecure.policymgr.clientssl.truststore: $truststore
    xasecure.policymgr.clientssl.truststore.password: $truststorepassword

HBASE:
  - config_type: hbase-site
    hbase.ssl.enabled: true
    hadoop.ssl.enabled: true
    hbase.rest.ssl.enabled: true
    hbase.rest.ssl.keystore.store: $keystorepassword
    hbase.rest.ssl.keystore.password: $keystorepassword
    hbase.rest.ssl.keystore.keypassword: $keystorepassword
    ssl.server.keystore.keypassword: $keystorepassword
    ssl.server.keystore.password: $keystorepassword
    ssl.server.keystore.location: $keystore

ATLAS:
  - config_type: application-properties
    atlas.enableTLS: true
    keystore.file: $keystore
    truststore.file: $truststore
    cert.stores.credential.provider.path: jceks://file//etc/atlas/conf/credentials.jceks

SPARK2:
  - config_type: yarn-site
    spark.authenticate: true

  - config_type: spark2-defaults
    spark.authenticate: true
    spark.authenticate.enableSaslEncryption: true
    spark.ssl.enabled: true
    spark.ssl.keyPassword: $keystorepassword
    spark.ssl.keyStore: $keystore
    spark.ssl.keyStorePassword: $keystorepassword
    spark.ssl.protocol: TLSv1.2
    spark.ssl.trustStore: $truststore
    spark.ssl.trustStorePassword: $truststorepassword
    spark.ui.https.enabled: true
    spark.ssl.historyServer.port: 18481
    spark.ssl.historyServer.enabled: true
    spark.ssl.historyServer.keystore: /etc/security/certificates/keystore.jks
    spark.ssl.historyServer.keyStorePassword: $keystorepassword
    spark.ssl.historyServer.truststore: /etc/security/certificates/truststore.jks
    spark.ssl.historyServer.trustStorePassword: $truststorepassword

  - config_type: spark2-hive-site-override
    hive.server2.transport.mode: http
    hive.server2.thrift.http.port: 10016
    hive.server2.http.endpoint: cliservice
    hive.server2.use.SSL: true
    hive.server2.keystore.path: $keystore
    hive.server2.keystore.password: $keystorepassword

  - config_type: livy2-conf
    livy.keystore: $keystore
    livy.keystore.password: $keystorepassword
    livy.key-password: $keystorepassword

STORM:
  - config_type: storm-site
    ui.https.port: 8740
    ui.https.keystore.type: jks
    ui.https.keystore.path: $keystore
    ui.https.keystore.password: $keystorepassword
    ui.https.key.password: $keystorepassword
    ui.https.truststore.path: $truststore
    ui.https.truststore.password: $truststorepassword
    ui.https.truststore.type: jks
    drpc.https.port: 3778
    drpc.https.keystore.type: jks
    drpc.https.keystore.path: $keystore
    drpc.https.keystore.password: $keystorepassword
    drpc.https.key.password: $keystorepassword
    drpc.https.truststore.path: $truststore
    drpc.https.truststore.password: $truststorepassword
    drpc.https.truststore.type: jks

NIFI:
  - config_type: nifi-ambari-config
    nifi.node.port: ' '

  - config_type: nifi-properties
    nifi.web.http.port: ' '
    nifi.security.keyPasswd: $keystorepassword
    nifi.security.keystorePasswd: $keystorepassword
    nifi.security.truststorePasswd: $truststorepassword

  - config_type: nifi-ambari-ssl-config
    nifi.toolkit.tls.token: ' '
    nifi.node.ssl.isenabled: true
    nifi.security.keystore: $keystore
    nifi.security.keystoreType: jks
    nifi.security.keystorePasswd: $keystorepassword
    nifi.security.keyPasswd: $keystorepassword
    nifi.security.truststore: $truststore
    nifi.security.truststoreType: jks
    nifi.security.truststorePasswd: $truststorepassword

  - config_type: ranger-nifi-plugin-properties
    nifi.authentication: SSL
    nifi.ssl.keystore: $keystore
    nifi.ssl.keystorePassword: $keystorepassword
    nifi.ssl.keystoreType: jks
    nifi.ssl.truststore: $truststore
    nifi.ssl.truststoreType: jks
    nifi.ssl.truststorePassword: $truststorepassword

  - config_type: ranger-nifi-security
    ranger.plugin.nifi.policy.rest.url: "{{config['configurations']['ranger-admin-site']['ranger.externalurl']}}"

  - config_type: ranger-nifi-policymgr-ssl
    xasecure.policymgr.clientssl.keystore: $keystore
    xasecure.policymgr.clientssl.keystore.password: $keystorepassword
    xasecure.policymgr.clientssl.truststore: $truststore
    xasecure.policymgr.clientssl.truststore.password: $truststorepassword

NIFI_REGISTRY:
  - config_type: nifi-registry-ambari-config

  - config_type: nifi-registry-ambari-ssl-config
    nifi.registry.ssl.isenabled: true

  - config_type: nifi-registry-ambari-ssl-config
    nifi.registry.security.keystore: $keystore
    nifi.registry.security.keystoreType: jks
    nifi.registry.security.keystorePasswd: $keystorepassword
    nifi.registry.security.keyPasswd: $keystorepassword
    nifi.registry.security.truststore: $truststore
    nifi.registry.security.truststoreType: jks
    nifi.registry.security.truststorePasswd: $truststorepassword

  - config_type: nifi-registry-properties
    nifi.registry.security.keystorePasswd: $keystorepassword
    nifi.registry.security.keyPasswd: $keystorepassword
    nifi.registry.security.truststorePasswd: $truststorepassword

AMBARI_METRICS:
  - config_type: ams-ssl-client
    ssl.client.truststore.location: $truststore
    ssl.client.truststore.password: $truststorepassword
    ssl.client.truststore.type: jks

  - config_type: ams-ssl-server
    ssl.server.keystore.alias: host_ssl
    ssl.server.keystore.keypassword: $keystorepassword
    ssl.server.keystore.location: $keystore
    ssl.server.keystore.password: $keystorepassword
    ssl.server.keystore.type: jks
    ssl.server.truststore.location: $truststore
    ssl.server.truststore.password: $truststorepassword
    ssl.server.truststore.type: jks

  - config_type: ams-grafana-ini
    ca_cert: /etc/pki/tls/certs/ca-bundle.crt
    cert_file: /etc/security/certificates/host.crt
    cert_key: /etc/security/certificates/host.key
    protocol: https

SMARTSENSE:
  - config_type: activity-zeppelin-site
    zeppelin.server.ssl.port: 9060
    zeppelin.ssl.key.manager.password: $keystorepassword
    zeppelin.ssl.keystore.password: $keystorepassword
    zeppelin.ssl.keystore.path: $keystore
    zeppelin.ssl.keystore.type: jks
    zeppelin.ssl.truststore.password: $truststorepassword
    zeppelin.ssl.truststore.path: $truststore
    zeppelin.ssl.truststore.type: jks
    zeppelin.ssl: true

REGISTRY:
  - config_type: registry-ssl-config
    registry.keyStorePassword: $keystorepassword
    registry.keyStorePath: $keystore
    registry.keyStoreType: jks
    registry.ssl.isenabled: true
    registry.trustStorePassword: $truststorepassword
    registry.trustStorePath: $truststore
    registry.trustStoreType: jks
